spring:
  application:
    name: netty-server

server:
  port: 6111

homon:
  netty:
    ioRate: 80
    port: ${server.port}
    host: 127.0.0.1
    thread:
      bosscnt: 1
      workcnt: 8
  zk:
    enable: true
    hosts: 127.0.0.1:21811
    watchPath: /
    digest: homon
    namespace: homon